[package]
name = "om-core"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio", "chrono"] }
tokio.workspace = true
log.workspace = true
displaydoc.workspace = true
thiserror.workspace = true
num_enum = "0.7.5"
chrono = { version = "0.4.42", features = ["serde"] }
om-core-proc = { version = "0.1.0", path = "../om-core-proc" }
const_format = "0.2.35"
serde = "1.0.228"
axum = { version = "0.8.7", features = ["macros"] }
